

 export CARGO_PKG_NAME=CAPTCHA

rustc --crate-name autocfg /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/autocfg-1.0.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=a15b754e5c98fdb4 -C extra-filename=-a15b754e5c98fdb4 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "autocfg*.bc" -exec cp {} bitcodes/autocfg.bc \;

rustc --crate-name cfg_if --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=51ffce3c8ac7f570 -C extra-filename=-51ffce3c8ac7f570 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "cfg_if*.bc" -exec cp {} bitcodes/cfg_if.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=4473f4c81a176658 -C extra-filename=-4473f4c81a176658 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.5/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="lazy_static"' --cfg 'feature="std"' -C metadata=ed5e1d2dcc97d1af -C extra-filename=-ed5e1d2dcc97d1af --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name lazy_static /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f10818e51509befc -C extra-filename=-f10818e51509befc --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "lazy_static*.bc" -exec cp {} bitcodes/lazy_static.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.5/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="lazy_static"' --cfg 'feature="std"' -C metadata=3d1fe4e08db2229f -C extra-filename=-3d1fe4e08db2229f --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=8849cac634aad883 -C extra-filename=-8849cac634aad883 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name scopeguard /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/scopeguard-1.1.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=195fa987cf856c09 -C extra-filename=-195fa987cf856c09 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "scopeguard*.bc" -exec cp {} bitcodes/scopeguard.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crc32fast-1.2.1/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=ece5c8b2920de1eb -C extra-filename=-ece5c8b2920de1eb --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.16/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="std"' -C metadata=a4f3a5f1f9290317 -C extra-filename=-a4f3a5f1f9290317 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name adler /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=302359016cc6fa99 -C extra-filename=-302359016cc6fa99 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "adler*.bc" -exec cp {} bitcodes/adler.bc \;

rustc --crate-name adler32 --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.2.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=a3f4188fb5cf079d -C extra-filename=-a3f4188fb5cf079d --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "adler32*.bc" -exec cp {} bitcodes/adler32.bc \;

rustc --crate-name either /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/either-1.6.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=7e69c64b82869840 -C extra-filename=-7e69c64b82869840 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "either*.bc" -exec cp {} bitcodes/either.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.2.1/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' -C metadata=83d9b8c8b3a74ce7 -C extra-filename=-83d9b8c8b3a74ce7 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name wasi --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/wasi-0.9.0+wasi-snapshot-preview1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=a16b2b2b4637bb45 -C extra-filename=-a16b2b2b4637bb45 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "wasi*.bc" -exec cp {} bitcodes/wasi.bc \;

rustc --crate-name ahash --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.4.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=66ca2bfe883bf40c -C extra-filename=-66ca2bfe883bf40c --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "ahash*.bc" -exec cp {} bitcodes/ahash.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.5/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=94fd2f2df9ce1c4c -C extra-filename=-94fd2f2df9ce1c4c --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name bytemuck --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.7.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=4193cbace969d5a0 -C extra-filename=-4193cbace969d5a0 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "bytemuck*.bc" -exec cp {} bitcodes/bytemuck.bc \;

rustc --crate-name byteorder --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=1554e5cc9a00111d -C extra-filename=-1554e5cc9a00111d --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "byteorder*.bc" -exec cp {} bitcodes/byteorder.bc \;

rustc --crate-name weezl --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/weezl-0.1.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=5de369b9fbd4780f -C extra-filename=-5de369b9fbd4780f --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "weezl*.bc" -exec cp {} bitcodes/weezl.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.126/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="std"' -C metadata=7b1ea0e1b94f3303 -C extra-filename=-7b1ea0e1b94f3303 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name ppv_lite86 --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/ppv-lite86-0.2.10/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="simd"' --cfg 'feature="std"' -C metadata=31ca042a297f0134 -C extra-filename=-31ca042a297f0134 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "ppv_lite86*.bc" -exec cp {} bitcodes/ppv_lite86.bc \;

rustc --crate-name color_quant /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/color_quant-1.1.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=7b2f05d0525d08e6 -C extra-filename=-7b2f05d0525d08e6 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "color_quant*.bc" -exec cp {} bitcodes/color_quant.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.64/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=1e6cc1c385c909af -C extra-filename=-1e6cc1c385c909af --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name scoped_threadpool /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=d23beba25c50b548 -C extra-filename=-d23beba25c50b548 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "scoped_threadpool*.bc" -exec cp {} bitcodes/scoped_threadpool.bc \;

rustc --crate-name itoa /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/itoa-0.4.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=3873ba2519240629 -C extra-filename=-3873ba2519240629 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "itoa*.bc" -exec cp {} bitcodes/itoa.bc \;

rustc --crate-name hound /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/hound-3.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=580cf11fd120469f -C extra-filename=-580cf11fd120469f --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "hound*.bc" -exec cp {} bitcodes/hound.bc \;

rustc --crate-name base64 --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/base64-0.13.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=62a3b27b5f52326a -C extra-filename=-62a3b27b5f52326a --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "base64*.bc" -exec cp {} bitcodes/base64.bc \;

rustc --crate-name miniz_oxide --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.3.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=ade9aa471ff21ddc -C extra-filename=-ade9aa471ff21ddc --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern adler32=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libadler32-a3f4188fb5cf079d.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "miniz_oxide*.bc" -exec cp {} bitcodes/miniz_oxide.bc \;

rustc --crate-name hashbrown --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="ahash"' --cfg 'feature="default"' --cfg 'feature="inline-more"' -C metadata=78145e31a5c6bebb -C extra-filename=-78145e31a5c6bebb --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern ahash=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libahash-66ca2bfe883bf40c.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "hashbrown*.bc" -exec cp {} bitcodes/hashbrown.bc \;

rustc --crate-name rgb --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rgb-0.8.27/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="as-bytes"' --cfg 'feature="bytemuck"' --cfg 'feature="default"' -C metadata=b7f7f3304c75c08f -C extra-filename=-b7f7f3304c75c08f --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern bytemuck=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libbytemuck-4193cbace969d5a0.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rgb*.bc" -exec cp {} bitcodes/rgb.bc \;

rustc --crate-name crossbeam_utils --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="lazy_static"' --cfg 'feature="std"' -C metadata=50ac413745160bc2 -C extra-filename=-50ac413745160bc2 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --extern lazy_static=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/liblazy_static-f10818e51509befc.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "crossbeam_utils*.bc" -exec cp {} bitcodes/crossbeam_utils.bc \;

rustc --crate-name getrandom --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.16/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="std"' -C metadata=77c943fbe0834a62 -C extra-filename=-77c943fbe0834a62 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --extern wasi=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libwasi-a16b2b2b4637bb45.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "getrandom*.bc" -exec cp {} bitcodes/getrandom.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.6.4/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' -C metadata=3cf885e99e4114de -C extra-filename=-3cf885e99e4114de --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern autocfg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps/libautocfg-a15b754e5c98fdb4.rlib --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.4.4/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="no_extern_crate_alloc"' -C metadata=071b39dd7f17181a -C extra-filename=-071b39dd7f17181a --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern autocfg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps/libautocfg-a15b754e5c98fdb4.rlib --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.14/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="i128"' --cfg 'feature="std"' -C metadata=5f385c95b8cf448b -C extra-filename=-5f385c95b8cf448b --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern autocfg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps/libautocfg-a15b754e5c98fdb4.rlib --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-integer-0.1.44/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="i128"' --cfg 'feature="std"' -C metadata=f6f9f0f05853b427 -C extra-filename=-f6f9f0f05853b427 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern autocfg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps/libautocfg-a15b754e5c98fdb4.rlib --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=93e5bf57408bfa96 -C extra-filename=-93e5bf57408bfa96 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern autocfg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps/libautocfg-a15b754e5c98fdb4.rlib --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-iter-0.1.42/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=b68b10d9e284ba67 -C extra-filename=-b68b10d9e284ba67 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern autocfg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps/libautocfg-a15b754e5c98fdb4.rlib --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.3.2/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=5788ef9b1771491b -C extra-filename=-5788ef9b1771491b --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern autocfg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps/libautocfg-a15b754e5c98fdb4.rlib --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name deflate --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/deflate-0.8.6/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=dd6e4b9db6f39e0b -C extra-filename=-dd6e4b9db6f39e0b --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern adler32=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libadler32-a3f4188fb5cf079d.rmeta --extern byteorder=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libbyteorder-1554e5cc9a00111d.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "deflate*.bc" -exec cp {} bitcodes/deflate.bc \;

rustc --crate-name crc32fast /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crc32fast-1.2.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=aeea83e93d6657b4 -C extra-filename=-aeea83e93d6657b4 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --cap-lints allow --cfg crc32fast_stdarchx86  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "crc32fast*.bc" -exec cp {} bitcodes/crc32fast.bc \;

rustc --crate-name gif --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/gif-0.11.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="raii_no_panic"' --cfg 'feature="std"' -C metadata=8020320062a35ac5 -C extra-filename=-8020320062a35ac5 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern color_quant=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcolor_quant-7b2f05d0525d08e6.rmeta --extern weezl=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libweezl-5de369b9fbd4780f.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "gif*.bc" -exec cp {} bitcodes/gif.bc \;

rustc --crate-name bitflags /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.2.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=e8ec85381a3f45e0 -C extra-filename=-e8ec85381a3f45e0 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow --cfg bitflags_const_fn  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "bitflags*.bc" -exec cp {} bitcodes/bitflags.bc \;

rustc --crate-name rand_core --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="getrandom"' --cfg 'feature="std"' -C metadata=c3b0cb8974d5c829 -C extra-filename=-c3b0cb8974d5c829 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern getrandom=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libgetrandom-77c943fbe0834a62.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rand_core*.bc" -exec cp {} bitcodes/rand_core.bc \;

rustc --crate-name libc /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=96c680abe739c42a -C extra-filename=-96c680abe739c42a --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow --cfg freebsd11 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_cfg_target_vendor  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "libc*.bc" -exec cp {} bitcodes/libc.bc \;

rustc --crate-name ryu --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=83b11376c321a09a -C extra-filename=-83b11376c321a09a --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow --cfg integer128 --cfg maybe_uninit  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "ryu*.bc" -exec cp {} bitcodes/ryu.bc \;

rustc --crate-name serde /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.126/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="std"' -C metadata=c34358ca5c157daa -C extra-filename=-c34358ca5c157daa --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow --cfg ops_bound --cfg core_reverse --cfg de_boxed_c_str --cfg de_boxed_path --cfg de_rc_dst --cfg core_duration --cfg integer128 --cfg range_inclusive --cfg num_nonzero --cfg serde_derive --cfg core_try_from --cfg num_nonzero_signed --cfg systemtime_checked_add  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "serde*.bc" -exec cp {} bitcodes/serde.bc \;

rustc --crate-name crossbeam_channel --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="crossbeam-utils"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=b52ca36309367c8e -C extra-filename=-b52ca36309367c8e --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --extern crossbeam_utils=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_utils-50ac413745160bc2.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "crossbeam_channel*.bc" -exec cp {} bitcodes/crossbeam_channel.bc \;

rustc --crate-name num_cpus /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num_cpus-1.13.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=4b913357074d86cb -C extra-filename=-4b913357074d86cb --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern libc=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/liblibc-96c680abe739c42a.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "num_cpus*.bc" -exec cp {} bitcodes/num_cpus.bc \;

rustc --crate-name rand_chacha --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_chacha-0.2.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="std"' -C metadata=73a8848159f4c640 -C extra-filename=-73a8848159f4c640 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern ppv_lite86=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libppv_lite86-31ca042a297f0134.rmeta --extern rand_core=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/librand_core-c3b0cb8974d5c829.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rand_chacha*.bc" -exec cp {} bitcodes/rand_chacha.bc \;

rustc --crate-name fallible_collections --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/fallible_collections-0.4.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=616254e251cfce25 -C extra-filename=-616254e251cfce25 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern hashbrown=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libhashbrown-78145e31a5c6bebb.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "fallible_collections*.bc" -exec cp {} bitcodes/fallible_collections.bc \;

rustc --crate-name memoffset /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.6.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=55fc07dfc98aa179 -C extra-filename=-55fc07dfc98aa179 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow --cfg tuple_ty --cfg allow_clippy --cfg maybe_uninit --cfg doctests --cfg raw_ref_macros  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "memoffset*.bc" -exec cp {} bitcodes/memoffset.bc \;

rustc --crate-name crossbeam_epoch --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="lazy_static"' --cfg 'feature="std"' -C metadata=72548fb7df6fe5d3 -C extra-filename=-72548fb7df6fe5d3 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --extern crossbeam_utils=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_utils-50ac413745160bc2.rmeta --extern lazy_static=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/liblazy_static-f10818e51509befc.rmeta --extern memoffset=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libmemoffset-55fc07dfc98aa179.rmeta --extern scopeguard=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libscopeguard-195fa987cf856c09.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "crossbeam_epoch*.bc" -exec cp {} bitcodes/crossbeam_epoch.bc \;

rustc --crate-name miniz_oxide --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.4.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="no_extern_crate_alloc"' -C metadata=e6a98da1c6a0ac4c -C extra-filename=-e6a98da1c6a0ac4c --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern adler=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libadler-302359016cc6fa99.rmeta --cap-lints allow --cfg has_alloc  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "miniz_oxide*.bc" -exec cp {} bitcodes/miniz_oxide.bc \;

rustc --crate-name num_traits /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.14/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="i128"' --cfg 'feature="std"' -C metadata=7b56aec63803eec5 -C extra-filename=-7b56aec63803eec5 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --cap-lints allow --cfg has_i128 --cfg has_to_int_unchecked  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "num_traits*.bc" -exec cp {} bitcodes/num_traits.bc \;

rustc --crate-name rand --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="getrandom"' --cfg 'feature="getrandom_package"' --cfg 'feature="libc"' --cfg 'feature="std"' -C metadata=0a86518449560f1c -C extra-filename=-0a86518449560f1c --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern getrandom_package=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libgetrandom-77c943fbe0834a62.rmeta --extern rand_chacha=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/librand_chacha-73a8848159f4c640.rmeta --extern rand_core=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/librand_core-c3b0cb8974d5c829.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rand*.bc" -exec cp {} bitcodes/rand.bc \;

rustc --crate-name png --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.16.8/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="deflate"' --cfg 'feature="png-encoding"' -C metadata=a781db739df632ba -C extra-filename=-a781db739df632ba --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern bitflags=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libbitflags-e8ec85381a3f45e0.rmeta --extern crc32fast=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrc32fast-aeea83e93d6657b4.rmeta --extern deflate=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libdeflate-dd6e4b9db6f39e0b.rmeta --extern miniz_oxide=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libminiz_oxide-ade9aa471ff21ddc.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "png*.bc" -exec cp {} bitcodes/png.bc \;

rustc --crate-name crossbeam_deque --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-deque-0.8.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="crossbeam-epoch"' --cfg 'feature="crossbeam-utils"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=5a72f4235f2fdf8e -C extra-filename=-5a72f4235f2fdf8e --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --extern crossbeam_epoch=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_epoch-72548fb7df6fe5d3.rmeta --extern crossbeam_utils=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_utils-50ac413745160bc2.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "crossbeam_deque*.bc" -exec cp {} bitcodes/crossbeam_deque.bc \;

rustc --crate-name rayon_core --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=c793053c80f9691c -C extra-filename=-c793053c80f9691c --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern crossbeam_channel=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_channel-b52ca36309367c8e.rmeta --extern crossbeam_deque=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_deque-5a72f4235f2fdf8e.rmeta --extern crossbeam_utils=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_utils-50ac413745160bc2.rmeta --extern lazy_static=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/liblazy_static-f10818e51509befc.rmeta --extern num_cpus=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_cpus-4b913357074d86cb.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rayon_core*.bc" -exec cp {} bitcodes/rayon_core.bc \;

rustc --crate-name flate2 --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.20/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="miniz_oxide"' --cfg 'feature="rust_backend"' -C metadata=33e7ad9c8ad5c59b -C extra-filename=-33e7ad9c8ad5c59b --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --extern crc32fast=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrc32fast-aeea83e93d6657b4.rmeta --extern libc=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/liblibc-96c680abe739c42a.rmeta --extern miniz_oxide=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libminiz_oxide-e6a98da1c6a0ac4c.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "flate2*.bc" -exec cp {} bitcodes/flate2.bc \;

rustc --crate-name lodepng --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/lodepng-3.4.6/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="rust_backend"' -C metadata=4623259a7964beee -C extra-filename=-4623259a7964beee --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern fallible_collections=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libfallible_collections-616254e251cfce25.rmeta --extern flate2=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libflate2-33e7ad9c8ad5c59b.rmeta --extern libc=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/liblibc-96c680abe739c42a.rmeta --extern rgb=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/librgb-b7f7f3304c75c08f.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "lodepng*.bc" -exec cp {} bitcodes/lodepng.bc \;

rustc --crate-name num_integer /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-integer-0.1.44/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="i128"' --cfg 'feature="std"' -C metadata=f386420dd4c9608e -C extra-filename=-f386420dd4c9608e --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern num_traits=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_traits-7b56aec63803eec5.rmeta --cap-lints allow --cfg has_i128  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "num_integer*.bc" -exec cp {} bitcodes/num_integer.bc \;

rustc --crate-name rayon --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=472f2ddadd86c8a6 -C extra-filename=-472f2ddadd86c8a6 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern crossbeam_deque=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcrossbeam_deque-5a72f4235f2fdf8e.rmeta --extern either=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libeither-7e69c64b82869840.rmeta --extern rayon_core=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/librayon_core-c793053c80f9691c.rmeta --cap-lints allow --cfg step_by --cfg min_const_generics  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rayon*.bc" -exec cp {} bitcodes/rayon.bc \;

rustc --crate-name num_rational --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.3.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=5278a1b2371c1ade -C extra-filename=-5278a1b2371c1ade --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern num_integer=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_integer-f386420dd4c9608e.rmeta --extern num_traits=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_traits-7b56aec63803eec5.rmeta --cap-lints allow --cfg has_int_exp_fmt  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "num_rational*.bc" -exec cp {} bitcodes/num_rational.bc \;

rustc --crate-name num_iter /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/num-iter-0.1.42/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=c23880bd306604f9 -C extra-filename=-c23880bd306604f9 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern num_integer=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_integer-f386420dd4c9608e.rmeta --extern num_traits=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_traits-7b56aec63803eec5.rmeta --cap-lints allow --cfg has_i128  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "num_iter*.bc" -exec cp {} bitcodes/num_iter.bc \;

rustc --crate-name serde_json --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.64/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=36093f8907b425e5 -C extra-filename=-36093f8907b425e5 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern itoa=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libitoa-3873ba2519240629.rmeta --extern ryu=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libryu-83b11376c321a09a.rmeta --extern serde=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libserde-c34358ca5c157daa.rmeta --cap-lints allow --cfg limb_width_32  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "serde_json*.bc" -exec cp {} bitcodes/serde_json.bc \;

rustc --crate-name jpeg_decoder /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/jpeg-decoder-0.1.22/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="rayon"' -C metadata=8320d90a73d3999a -C extra-filename=-8320d90a73d3999a --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern rayon=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/librayon-472f2ddadd86c8a6.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "jpeg_decoder*.bc" -exec cp {} bitcodes/jpeg_decoder.bc \;

rustc --crate-name tiff --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/tiff-0.6.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=2bb437c1ff0535ab -C extra-filename=-2bb437c1ff0535ab --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern jpeg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libjpeg_decoder-8320d90a73d3999a.rmeta --extern miniz_oxide=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libminiz_oxide-e6a98da1c6a0ac4c.rmeta --extern weezl=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libweezl-5de369b9fbd4780f.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "tiff*.bc" -exec cp {} bitcodes/tiff.bc \;

rustc --crate-name image --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="bmp"' --cfg 'feature="dds"' --cfg 'feature="default"' --cfg 'feature="dxt"' --cfg 'feature="farbfeld"' --cfg 'feature="gif"' --cfg 'feature="hdr"' --cfg 'feature="ico"' --cfg 'feature="jpeg"' --cfg 'feature="jpeg_rayon"' --cfg 'feature="png"' --cfg 'feature="pnm"' --cfg 'feature="scoped_threadpool"' --cfg 'feature="tga"' --cfg 'feature="tiff"' --cfg 'feature="webp"' -C metadata=52c9823a78e512a2 -C extra-filename=-52c9823a78e512a2 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern bytemuck=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libbytemuck-4193cbace969d5a0.rmeta --extern byteorder=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libbyteorder-1554e5cc9a00111d.rmeta --extern color_quant=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcolor_quant-7b2f05d0525d08e6.rmeta --extern gif=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libgif-8020320062a35ac5.rmeta --extern jpeg=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libjpeg_decoder-8320d90a73d3999a.rmeta --extern num_iter=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_iter-c23880bd306604f9.rmeta --extern num_rational=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_rational-5278a1b2371c1ade.rmeta --extern num_traits=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libnum_traits-7b56aec63803eec5.rmeta --extern png=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libpng-a781db739df632ba.rmeta --extern scoped_threadpool=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libscoped_threadpool-d23beba25c50b548.rmeta --extern tiff=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libtiff-2bb437c1ff0535ab.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "image*.bc" -exec cp {} bitcodes/image.bc \;

rustc --crate-name captcha /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/captcha-0.0.8/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=550b46d837cc95cd -C extra-filename=-550b46d837cc95cd --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern base64=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libbase64-62a3b27b5f52326a.rmeta --extern hound=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libhound-580cf11fd120469f.rmeta --extern image=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libimage-52c9823a78e512a2.rmeta --extern lodepng=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/liblodepng-4623259a7964beee.rmeta --extern rand=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/librand-0a86518449560f1c.rmeta --extern serde_json=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libserde_json-36093f8907b425e5.rmeta --cap-lints allow  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "captcha*.bc" -exec cp {} bitcodes/captcha.bc \;

rustc --crate-name wcaptcha --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=2e2489508592db30 -C extra-filename=-2e2489508592db30 --out-dir temp --target wasm32-wasi -C incremental=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/incremental -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/debug/deps --extern captcha=/Users/javierca/Documents/Develop/fastly4edge/link_captcha/rust/target/wasm32-wasi/debug/deps/libcaptcha-550b46d837cc95cd.rmeta  -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "wcaptcha*.bc" -exec cp {} bitcodes/wcaptcha.bc \;

python3 sanitizer.py bitcodes

$LINKER $(find bitcodes -name "*.bc") -o bitcodes/captcha.all.bc