[package]
name = "speed_tester"
version = "0.1.0"
authors = ["Jacarte <javierca@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.2"
structopt = "0.3.2"
log = "0.4.8"
