python3 analyze_traces.py results/crypto_aead_chacha20poly1305_ietf_decrypt_detached.result.json crypto_aead_chacha20poly1305_ietf_decrypt_detached instrumentedPureRandom libsodium maps/libsodium_enumeratio.json

python3 analyze_traces.py results/crypto_aead_chacha20poly1305_ietf_encrypt_detached.result.json crypto_aead_chacha20poly1305_ietf_encrypt_detached instrumentedPureRandom libsodium maps/libsodium_enumeratio.json

python3 analyze_traces.py results/crypto_core_ed25519_scalar_random.result.json crypto_core_ed25519_scalar_random instrumentedPureRandom libsodium maps/libsodium_enumeratio.json


python3 analyze_traces.py results/crypto_core_ed25519_scalar_invert.result.json crypto_core_ed25519_scalar_invert instrumentedPureRandom libsodium maps/libsodium_enumeratio.json

#python3 analyze_traces.py results/crypto_core_ed25519_scalar_complement.result.json crypto_core_ed25519_scalar_complement instrumentedPureRandom libsodium


python3 analyze_traces.py results/bin2base64.result.json bin2base64 instrumentedPureRandom libsodium maps/libsodium_enumeratio.json