#python3 create_graph.py maps/libsodium/nodes.txt maps/libsodium/edges.txt maps/libsodium/zero.txt libsodium  
 python3 create_graph_from_execution.py maps/libsodium.txt libsodium stability/rq11.stability.json results/bin2base64.result.json bin2base64 results/crypto_aead_chacha20poly1305_ietf_decrypt_detached.result.json crypto_aead_chacha20poly1305_ietf_decrypt_detached results/crypto_aead_chacha20poly1305_ietf_encrypt_detached.result.json crypto_aead_chacha20poly1305_ietf_encrypt_detached results/crypto_core_ed25519_scalar_random.result.json crypto_core_ed25519_scalar_random  results/crypto_core_ed25519_scalar_invert.result.json crypto_core_ed25519_scalar_invert  results/crypto_core_ed25519_scalar_complement.result.json crypto_core_ed25519_scalar_complement

# bin2base64 1 crypto_aead_chacha20poly1305_ietf_decrypt_detached 2 crypto_aead_chacha20poly1305_ietf_encrypt_detached 3 crypto_core_ed25519_scalar_random 4 crypto_core_ed25519_scalar_invert 5 crypto_core_ed25519_scalar_complement 6
#python3 create_graph_from_execution.py maps/libsodium.txt  libsodium  stability/rq11.stability.json

# python3 create_pop_nodes.py ../../../speedTest/python_scripts/out/pops.json  libsodium
# python3 create_static_cfg.py static_maps/libsodium.multivariant.csv maps/libsodium.txt libsodium




#python3 create_call_edges.py results/crypto_aead_chacha20poly1305_ietf_encrypt_detached.result.json crypto_aead_chacha20poly1305_ietf_encrypt_detached instrumentedPureRandom libsodium#

#python3 create_call_edges.py results/crypto_core_ed25519_scalar_invert.result.json crypto_core_ed25519_scalar_invert instrumentedPureRandom libsodium


#python3 create_call_edges.py results/crypto_core_ed25519_scalar_complement.result.json crypto_core_ed25519_scalar_complement instrumentedPureRandom libsodium


#python3 create_call_edges.py results/crypto_core_ed25519_scalar_random.result.json crypto_core_ed25519_scalar_random instrumentedPureRandom libsodium


#python3 create_call_edges.py results/bin2base64.result.json bin2base64 instrumentedPureRandom libsodium
#python3 create_call_edges.py results/crypto_aead_chacha20poly1305_ietf_decrypt_detached.result.json crypto_aead_chacha20poly1305_ietf_decrypt_detached instrumentedDeterministic
#python3 create_call_edges.py results/crypto_aead_chacha20poly1305_ietf_decrypt_detached.result.json crypto_aead_chacha20poly1305_ietf_decrypt_detached 
