
rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.16/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="std"' -C metadata=a4f3a5f1f9290317 -C extra-filename=-a4f3a5f1f9290317 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name wasi --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/wasi-0.9.0+wasi-snapshot-preview1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=a16b2b2b4637bb45 -C extra-filename=-a16b2b2b4637bb45 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "wasi*.bc" -exec cp {} bitcodes/wasi.bc \;

rustc --crate-name cfg_if --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=51ffce3c8ac7f570 -C extra-filename=-51ffce3c8ac7f570 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "cfg_if*.bc" -exec cp {} bitcodes/cfg_if.bc \;

rustc --crate-name ppv_lite86 --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/ppv-lite86-0.2.10/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="simd"' --cfg 'feature="std"' -C metadata=31ca042a297f0134 -C extra-filename=-31ca042a297f0134 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "ppv_lite86*.bc" -exec cp {} bitcodes/ppv_lite86.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=4473f4c81a176658 -C extra-filename=-4473f4c81a176658 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name checked_int_cast /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/checked_int_cast-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=b0118a623982fadf -C extra-filename=-b0118a623982fadf --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "checked_int_cast*.bc" -exec cp {} bitcodes/checked_int_cast.bc \;

rustc --crate-name lazy_static /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f10818e51509befc -C extra-filename=-f10818e51509befc --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "lazy_static*.bc" -exec cp {} bitcodes/lazy_static.bc \;

rustc --crate-name qrcode --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/qrcode-0.11.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1b38f52d05bc1fc0 -C extra-filename=-1b38f52d05bc1fc0 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --extern checked_int_cast=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/libchecked_int_cast-b0118a623982fadf.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "qrcode*.bc" -exec cp {} bitcodes/qrcode.bc \;

rustc --crate-name getrandom --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.16/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="std"' -C metadata=77c943fbe0834a62 -C extra-filename=-77c943fbe0834a62 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/libcfg_if-51ffce3c8ac7f570.rmeta --extern wasi=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/libwasi-a16b2b2b4637bb45.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "getrandom*.bc" -exec cp {} bitcodes/getrandom.bc \;

rustc --crate-name libc /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=96c680abe739c42a -C extra-filename=-96c680abe739c42a --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --cap-lints allow --cfg freebsd11 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_cfg_target_vendor -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "libc*.bc" -exec cp {} bitcodes/libc.bc \;

rustc --crate-name rand_core --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="getrandom"' --cfg 'feature="std"' -C metadata=c3b0cb8974d5c829 -C extra-filename=-c3b0cb8974d5c829 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --extern getrandom=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/libgetrandom-77c943fbe0834a62.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rand_core*.bc" -exec cp {} bitcodes/rand_core.bc \;

rustc --crate-name rand_chacha --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_chacha-0.2.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="std"' -C metadata=73a8848159f4c640 -C extra-filename=-73a8848159f4c640 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --extern ppv_lite86=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/libppv_lite86-31ca042a297f0134.rmeta --extern rand_core=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/librand_core-c3b0cb8974d5c829.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rand_chacha*.bc" -exec cp {} bitcodes/rand_chacha.bc \;

rustc --crate-name rand --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="getrandom"' --cfg 'feature="getrandom_package"' --cfg 'feature="libc"' --cfg 'feature="std"' -C metadata=0a86518449560f1c -C extra-filename=-0a86518449560f1c --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --extern getrandom_package=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/libgetrandom-77c943fbe0834a62.rmeta --extern rand_chacha=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/librand_chacha-73a8848159f4c640.rmeta --extern rand_core=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/librand_core-c3b0cb8974d5c829.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "rand*.bc" -exec cp {} bitcodes/rand.bc \;

rustc --crate-name multivariant_zxing --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=963ca439b769e32a -C extra-filename=-963ca439b769e32a --out-dir temp --target wasm32-wasi -C incremental=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/incremental -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/debug/deps --extern lazy_static=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/liblazy_static-f10818e51509befc.rmeta --extern libc=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/liblibc-96c680abe739c42a.rmeta --extern qrcode=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/libqrcode-1b38f52d05bc1fc0.rmeta --extern rand=/Users/javierca/Documents/Develop/fastly4edge/link_qrcode/rust/target/wasm32-wasi/debug/deps/librand-0a86518449560f1c.rmeta -Clto -C embed-bitcode=yes --emit=llvm-bc -C linker-plugin-lto

find temp -name "multivariant_zxing*.bc" -exec cp {} bitcodes/multivariant_zxing.bc \;

python3 sanitizer.py bitcodes

$LINKER $(find bitcodes -name "*.bc") -o bitcodes/all.bc