
rustc --crate-name build_script_build --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.16/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="std"' -C metadata=1a7efb5a9835f1d1 -C extra-filename=-1a7efb5a9835f1d1 --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name wasi --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/wasi-0.9.0+wasi-snapshot-preview1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=708bdee707f8d81e -C extra-filename=-708bdee707f8d81e --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "wasi*.bc" -exec cp {} bitcodes/wasi.bc \;

rustc --crate-name cfg_if --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=d09cb12db2843d8a -C extra-filename=-d09cb12db2843d8a --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "cfg_if*.bc" -exec cp {} bitcodes/cfg_if.bc \;

rustc --crate-name build_script_build /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=84d75259a9bbba3d -C extra-filename=-84d75259a9bbba3d --out-dir temp -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "build_script_build*.bc" -exec cp {} bitcodes/build_script_build.bc \;

rustc --crate-name ppv_lite86 --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/ppv-lite86-0.2.10/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="simd"' --cfg 'feature="std"' -C metadata=edd05c98ec316bb8 -C extra-filename=-edd05c98ec316bb8 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "ppv_lite86*.bc" -exec cp {} bitcodes/ppv_lite86.bc \;

rustc --crate-name lazy_static /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=d4de8ca3c20977b6 -C extra-filename=-d4de8ca3c20977b6 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "lazy_static*.bc" -exec cp {} bitcodes/lazy_static.bc \;

rustc --crate-name checked_int_cast /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/checked_int_cast-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=e157b342dc5031db -C extra-filename=-e157b342dc5031db --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "checked_int_cast*.bc" -exec cp {} bitcodes/checked_int_cast.bc \;

rustc --crate-name qrcode --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/qrcode-0.11.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=d67e74d42fb2ed69 -C extra-filename=-d67e74d42fb2ed69 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --extern checked_int_cast=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libchecked_int_cast-e157b342dc5031db.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "qrcode*.bc" -exec cp {} bitcodes/qrcode.bc \;

rustc --crate-name getrandom --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.16/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="std"' -C metadata=3f3f5b753ce71fb4 -C extra-filename=-3f3f5b753ce71fb4 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --extern cfg_if=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libcfg_if-d09cb12db2843d8a.rmeta --extern wasi=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libwasi-708bdee707f8d81e.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "getrandom*.bc" -exec cp {} bitcodes/getrandom.bc \;

rustc --crate-name libc /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=932d039283a2d14a -C extra-filename=-932d039283a2d14a --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --cap-lints allow --cfg freebsd11 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_cfg_target_vendor -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "libc*.bc" -exec cp {} bitcodes/libc.bc \;

rustc --crate-name rand_core --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="alloc"' --cfg 'feature="getrandom"' --cfg 'feature="std"' -C metadata=87a413a0cbad5f7f -C extra-filename=-87a413a0cbad5f7f --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --extern getrandom=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libgetrandom-3f3f5b753ce71fb4.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "rand_core*.bc" -exec cp {} bitcodes/rand_core.bc \;

rustc --crate-name rand_chacha --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_chacha-0.2.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="std"' -C metadata=8974650b07b30ff7 -C extra-filename=-8974650b07b30ff7 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --extern ppv_lite86=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libppv_lite86-edd05c98ec316bb8.rmeta --extern rand_core=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/librand_core-87a413a0cbad5f7f.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "rand_chacha*.bc" -exec cp {} bitcodes/rand_chacha.bc \;

rustc --crate-name rand --edition=2018 /Users/javierca/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.7.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="getrandom"' --cfg 'feature="getrandom_package"' --cfg 'feature="libc"' --cfg 'feature="std"' -C metadata=bbc07a168b6c7643 -C extra-filename=-bbc07a168b6c7643 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --extern getrandom_package=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libgetrandom-3f3f5b753ce71fb4.rmeta --extern rand_chacha=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/librand_chacha-8974650b07b30ff7.rmeta --extern rand_core=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/librand_core-87a413a0cbad5f7f.rmeta --cap-lints allow -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "rand*.bc" -exec cp {} bitcodes/rand.bc \;

rustc --crate-name qrcode_simple --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=0d43b7418ae24686 -C extra-filename=-0d43b7418ae24686 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --extern lazy_static=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/liblazy_static-d4de8ca3c20977b6.rmeta --extern libc=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/liblibc-932d039283a2d14a.rmeta --extern qrcode=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libqrcode-d67e74d42fb2ed69.rmeta --extern rand=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/librand-bbc07a168b6c7643.rmeta -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "qrcode_simple*.bc" -exec cp {} bitcodes/qrcode_simple.bc \;

rustc --crate-name main --edition=2018 src/bin/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off -C metadata=9068df4b28083ae3 -C extra-filename=-9068df4b28083ae3 --out-dir temp --target wasm32-wasi -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps -L dependency=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/release/deps --extern lazy_static=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/liblazy_static-d4de8ca3c20977b6.rlib --extern libc=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/liblibc-932d039283a2d14a.rlib --extern qrcode=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libqrcode-d67e74d42fb2ed69.rlib --extern qrcode_simple=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/libqrcode_simple-0d43b7418ae24686.rlib --extern rand=/Users/javierca/Documents/Develop/fastly4edge/fastly/link_qrcode/rust/target/wasm32-wasi/release/deps/librand-bbc07a168b6c7643.rlib -Clto -C embed-bitcode=yes --emit=llvm-bc

find temp -name "main*.bc" -exec cp {} bitcodes/main.bc \;

python3 sanitizer.py bitcodes

$LINKER $(find bitcodes -name "*.bc") -o bitcodes/all.bc